lightning:
  callbacks:
    image_logger:
      target: lvdm.utils.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: false
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: '{epoch:06}-{step:09}'
        save_weights_only: false
        every_n_epochs: 300
        every_n_train_steps: null
  trainer:
    benchmark: true
    batch_size: 1
    num_workers: 38
    num_nodes: 1
    accumulate_grad_batches: 2
    max_epochs: 2000
    accelerator: cuda
    gpus: 0,1,
  modelcheckpoint:
    target: pytorch_lightning.callbacks.ModelCheckpoint
    params:
      every_n_epochs: 1
      filename: '{epoch:04}-{step:06}'
